### ISSUE TITLE
RFC: Implement Pre/Post hooks

### ISSUE THREAD

**Issue by lestrrat** [shogo82148/go-sql-proxy#2]
Can you please check this?
https://github.com/lestrrat/go-sql-proxy/commit/a5e2df5cf337fd54fd16abad0474142b6ac26140

# What is this?
I want to check if this sort of change is acceptable before going any further. I added some hooks that allows me to put timers.

Pseudocode:
```go
   &Hooks{
        PreExec: func( .... ) (interface{}, error) {
             log.Printf("Executing  ....")
             return time.Now(), nil // this time.Now() is passed to Post* func
        },
        PostExec: func(ctx interface{}, ...) error {
             log.Printf("elapsed time: %s", time.Since(ctx.(time.Time)).String())
             return nil
        }
   }
```

The point being that I want this to ALWAYS execute, regardless of what the other hooks are doing.

Does this sound like something you can consider merging?

**Comment by mattn** [comment]
:+1:

**Comment by shogo82148** [comment]
:+1:
