### ISSUE TITLE
Go-sql-proxy changes behavior of some sql driver

### ISSUE THREAD

**Issue by Talos208** [shogo82148/go-sql-proxy#8]
`proxy.Conn` implements only `driver.Conn` interface.

But connection of some sql driver (e.g. [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql) ) have `Query(string,  []driver.Value) (driver.Rows, error)` method. It implements both `driver.Conn` and `driver.Queryer` .

When `conn.Query()` called without `conn.Prepare()`, it makes some behavior difference between driver itself and proxied one.

 `proxy.Conn` should implements also `driver.Queryer` .

**Comment by shogo82148** [comment]
I implemented `driver.Queryer` and some other interfaces ( https://github.com/shogo82148/go-sql-proxy/pull/9 )
please you try it.

**Comment by Talos208** [comment]
I tried #9  with my code. It seems to work well.

Thx!

**Comment by shogo82148** [comment]
thank you for trying!
I merged #9
